spring:
  config:
    activate:
      on-profile: prod
  application:
    name: gateway-service
  main:
    web-application-type: reactive
    cloud:
      gateway:
        routes: # Spring Cloud Gateway의 라우팅 설정
          - id: order-service # 라우트 식별자
            uri: lb://order-service # 'order-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
            predicates:
              - Path=/orders/**
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/products/**
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/auth/**
        discovery:
          locator:
            enabled: true # 서비스 디스커버리를 통해 동적으로 라우트를 생성
server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
service:
  jwt:
    secret-key: "b3b86c00b9abbff14e9c54ebb6ec15d205ffe19f4aaf86a00a7b89a5e9893fd16e712ba950f594d8895186f4ba49f3ce061ba941ab8bbdd21c94f61ee1c359dd"